(defun merge-worker (l a b)
  (cond ((and (null a) (null b)) l)
        ((null a)
         (merge-worker (append l (list (first b)))
                       a
                       (rest b)))
        ((null b)
         (merge-worker (append l (list (first a)))
                       (rest a)
                       b))
        ((< (first a) (first b))
         (merge-worker (append l (list (first a)))
                       (rest a)
                       b))
        ((>= (first a) (first b))
         (merge-worker (append l (list (first b)))
                       a
                       (rest b)))))

(defun first-half (l)
  (subseq l 0 (floor (length l) 2)))
(defun last-half (l)
  (subseq l (floor (length l) 2) (length l)))

(defun merge-sort (l)
  (cond ((null l) nil)
        ((= (length l) 1) l)
        (T (merge-worker '()
                         (merge-sort (first-half l))
                         (merge-sort (last-half  l))))))

(setq random-list (loop :for x := (random 1000001) :repeat 1000 :collect x))
(print (merge-sort random-list))
